/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package informatikhemsida;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mike_
 */
public class BokaMoteFonster extends javax.swing.JFrame {
 DataAccess access = new DataAccess("admin", "team15");
    /** Creates new form BokaMoteFonster */
    public BokaMoteFonster() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d1 = new javax.swing.JDialog();
        tfTid = new javax.swing.JTextField();
        tfDatum = new javax.swing.JTextField();
        btnboka = new javax.swing.JButton();
        tfMoteMejl = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tfTaBortM = new javax.swing.JTextField();
        btaBort = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfKontID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfDeltagare = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout d1Layout = new javax.swing.GroupLayout(d1.getContentPane());
        d1.getContentPane().setLayout(d1Layout);
        d1Layout.setHorizontalGroup(
            d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        d1Layout.setVerticalGroup(
            d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfTid.setText("tid");
        tfTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTidActionPerformed(evt);
            }
        });

        tfDatum.setText("datum");
        tfDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDatumActionPerformed(evt);
            }
        });

        btnboka.setText("Boka möte");
        btnboka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbokaActionPerformed(evt);
            }
        });

        tfMoteMejl.setText("Mejladress");

        jButton1.setText("Hem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfTaBortM.setText("ML Nummer");

        btaBort.setText("Ta bort");
        btaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btaBortActionPerformed(evt);
            }
        });

        jLabel1.setText("Ta bort möte, skriv Mötesledare nummer. ");

        tfKontID.setText("Konto ID");
        tfKontID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKontIDActionPerformed(evt);
            }
        });

        jLabel2.setText("*Mötesledare");

        tfDeltagare.setText("Konto ID");

        jLabel3.setText("*Deltagare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfKontID)
                                    .addComponent(tfMoteMejl, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(tfDeltagare))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addComponent(tfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btaBort)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTid, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTaBortM, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnboka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTaBortM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btaBort))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tfTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMoteMejl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfKontID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfDeltagare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnboka)
                            .addComponent(jButton1))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbokaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbokaActionPerformed
        
       String tid = tfTid.getText();
       String datum = tfDatum.getText();
       String mejl = tfMoteMejl.getText();
       String motesledare = tfKontID.getText(); 
       String deltagare = tfDeltagare.getText(); 
      
   
       if ( !tid.matches("..:.*")){
       JOptionPane.showMessageDialog(this, "fel tidformat, skriv XX:XX");
       
     
       }
        if ( !datum.matches("[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]*")){
       JOptionPane.showMessageDialog(this, "fel datumformat, skriv XXXX-XX-XX");
       
        }
       if ( !mejl.contains("@")){
       JOptionPane.showMessageDialog(this, " Ogiltig mailadress");
       }
       
       
     try {
         access.setMote(tid, datum, motesledare, deltagare);
     } catch (ClassNotFoundException | SQLException ex) {
         Logger.getLogger(BokaMoteFonster.class.getName()).log(Level.SEVERE, null, ex);
     }

    }//GEN-LAST:event_btnbokaActionPerformed

    private void tfDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDatumActionPerformed

    private void btaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btaBortActionPerformed
        String delete = tfTaBortM.getText();
     try {
         access.deleteMote(delete);
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(BokaMoteFonster.class.getName()).log(Level.SEVERE, null, ex);
     } catch (SQLException ex) {
         Logger.getLogger(BokaMoteFonster.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_btaBortActionPerformed

    private void tfKontIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKontIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKontIDActionPerformed

    private void tfTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BokaMoteFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BokaMoteFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BokaMoteFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BokaMoteFonster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BokaMoteFonster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btaBort;
    private javax.swing.JButton btnboka;
    private javax.swing.JDialog d1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfDatum;
    private javax.swing.JTextField tfDeltagare;
    private javax.swing.JTextField tfKontID;
    private javax.swing.JTextField tfMoteMejl;
    private javax.swing.JTextField tfTaBortM;
    private javax.swing.JTextField tfTid;
    // End of variables declaration//GEN-END:variables

}
