/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informatikhemsida;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Diana Jumaili
 */

@SuppressWarnings("serial")
public class SkapaBloggInläggFonster extends javax.swing.JFrame {

    DataAccess access = new DataAccess("admin", "team15");

    /**
     * Creates new form SkapaBloggInläggFonster
     */
    public SkapaBloggInläggFonster() throws ClassNotFoundException, SQLException {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);

        cbBloggKategori.removeAllItems();

        ArrayList<String> kategorier = access.getKolumnFrånTabell(2, "Kategori", "KategoriID");

        for (String kategori : kategorier) {
            cbBloggKategori.addItem(kategori);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbBloggKategori = new javax.swing.JComboBox<>();
        btnSkapaBloggInlägg = new javax.swing.JButton();
        tfBloggInläggRubrik = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taBloggInläggInnehåll = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbBloggKategori.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSkapaBloggInlägg.setText("Posta inlägg");
        btnSkapaBloggInlägg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaBloggInläggActionPerformed(evt);
            }
        });

        taBloggInläggInnehåll.setColumns(20);
        taBloggInläggInnehåll.setRows(5);
        taBloggInläggInnehåll.setText("Innehåll");
        taBloggInläggInnehåll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taBloggInläggInnehållMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taBloggInläggInnehåll);

        jLabel1.setText("Rubrik:");

        jLabel2.setText("Kategori:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(
                                        btnSkapaBloggInlägg, javax.swing.GroupLayout.PREFERRED_SIZE, 184,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27))
                        .addGroup(layout.createSequentialGroup().addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2).addGap(109, 109, 109))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(tfBloggInläggRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164,
                                        Short.MAX_VALUE)
                                .addComponent(cbBloggKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 123,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)))));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1).addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfBloggInläggRubrik, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbBloggKategori, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55).addComponent(btnSkapaBloggInlägg).addGap(39, 39, 39)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkapaBloggInläggActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSkapaBloggInläggActionPerformed
        boolean succe = false;

        String kategori = null;

        kategori = cbBloggKategori.getSelectedItem().toString();

        if (tfBloggInläggRubrik.getText().isEmpty() || taBloggInläggInnehåll.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Försök igen");
        } else {
            try {
                access.skapaBloggInlägg(tfBloggInläggRubrik.getText(), taBloggInläggInnehåll.getText(), kategori);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SkapaBloggInläggFonster.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(SkapaBloggInläggFonster.class.getName()).log(Level.SEVERE, null, ex);
            }
            succe = true;

            if (succe = true) {
                JOptionPane.showMessageDialog(null, "Inlägget har skapats!");
                this.setVisible(false);
                new StartsidaFonster().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Något gick fel");
            }
        }

    }// GEN-LAST:event_btnSkapaBloggInläggActionPerformed

    private void taBloggInläggInnehållMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_taBloggInläggInnehållMouseClicked
        taBloggInläggInnehåll.setText(" ");
    }// GEN-LAST:event_taBloggInläggInnehållMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkapaBloggInläggFonster.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkapaBloggInläggFonster.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkapaBloggInläggFonster.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkapaBloggInläggFonster.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SkapaBloggInläggFonster().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SkapaBloggInläggFonster.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(SkapaBloggInläggFonster.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSkapaBloggInlägg;
    private javax.swing.JComboBox<String> cbBloggKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taBloggInläggInnehåll;
    private javax.swing.JTextField tfBloggInläggRubrik;
    // End of variables declaration//GEN-END:variables
}
