/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informatikhemsida;

import java.awt.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author Admin
 */
public class VisaSchema extends javax.swing.JFrame {
    String connectionURL = null;
    Connection con;
    Statement st = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    String NamnDatum;
    DataAccess access = new DataAccess ("admin","team15" );

    /**
     * Creates new form VisaSchema
     */
    public VisaSchema() throws SQLException, ClassNotFoundException {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ArrayList<String> datum = access.hamtaMoteDatum();
        cbe.setModel(new DefaultComboBoxModel<String> (datum.toArray(new String [2])));
        //hamtaDatumen();
        

    } 
    public void hamtaDatumen(){
try{
    ArrayList<HashMap<String,String>> ListaDatum = access.connectionURL(
     "select Datum from möte");
    for (HashMap<String,String> Lista:ListaDatum){
        String totalaDatum = Lista.get("Datum");
        //cbe.addItem(totalaDatum);
    }
     
 }
 catch(Exception e){
     
 }
    }               

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbe = new javax.swing.JComboBox<>();
        tfMötesTid = new javax.swing.JTextField();
        TfM = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 240, 47, 32);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(54, 85, 0, 0);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(77, 169, 0, 0);

        cbe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbeActionPerformed(evt);
            }
        });
        getContentPane().add(cbe);
        cbe.setBounds(10, 70, 140, 26);

        tfMötesTid.setText("             Tid");
        tfMötesTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMötesTidActionPerformed(evt);
            }
        });
        getContentPane().add(tfMötesTid);
        tfMötesTid.setBounds(200, 70, 100, 30);

        TfM.setText("   Mötesledare");
        TfM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfMActionPerformed(evt);
            }
        });
        getContentPane().add(TfM);
        TfM.setBounds(360, 70, 100, 30);

        jTextField2.setText("  Deltagare");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(500, 70, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // DataAccess access = new DataAccess("admin","team15");
       // ArrayList<String> HamtaDatum = new ArrayList<String>();
        //try {
          //  HamtaDatum = access.hamtaMote();
            
          //for(String datum : HamtaDatum)
            //{
              //  taVisaSchema.setText(datum); 
            
            //}
        //} catch (ClassNotFoundException | SQLException ex) {
          //  Logger.getLogger(VisaSchema.class.getName()).log(Level.SEVERE, null, ex);
        //}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbeActionPerformed
//DefaultListModel DatumLista = new DefaultListModel();
//Object c = cbe.getSelectedItem();
 //NamnDatum = String.valueOf(c);
 
    }//GEN-LAST:event_cbeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            
        try {
            String tid = access.visaSchemaTid(cbe);
            String mLedare = access.visaMöteledare(cbe);

            tfMötesTid.setText(tid);
            TfM.setText(mLedare);

        } catch (SQLException ex) {
            Logger.getLogger(VisaSchema.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VisaSchema.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfMötesTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMötesTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMötesTidActionPerformed

    private void TfMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaSchema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaSchema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaSchema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaSchema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    try {
                        new VisaSchema().setVisible(true);
                        
                        
                    } catch (ClassNotFoundException | SQLException ex) {
                        Logger.getLogger(VisaSchema.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfM;
    private javax.swing.JComboBox<String> cbe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField tfMötesTid;
    // End of variables declaration//GEN-END:variables
}
